--- !ruby/object:Deployment 
apaches: 
- !ruby/object:Apache 
  name: tabula
  port_balancer: !ruby/object:HAProxySocketBalancer
    balanced_group: jboss_pair
    balanced_servers:
    - "primary"
    - "secondary"
    current_jboss:
    - "primary"
    - "secondary"
    haproxy: !ruby/object:HAProxy::SocketReader
      path: "/var/run/haproxy.stat"
  apache_dir: "/usr/local/apache"
  restart_command: "echo 'not restarting apache' "
  state: balanced
build_status: starting
app: "tabula"
war_names:
- courses
- home
- profiles
checkout_base: "/var/src/checkout"
archive_dir: "/var/src/archive"
branch: "master"
build_user: "build"
builder: !ruby/object:MavenBuilder
  skipTests: true
  goal: "clean package"
jbosses: 
  tabula:
  - !ruby/object:Jboss 
    deployment_state: old
    name: tabula-primary
    haproxy_name: primary
    port: "8080"
    state: running
    mode: smf
    stop_command: "/usr/sbin/svcadm disable -s jboss:"  
    test_path: /home/test/up
    requests: 
       /home/test/up: 200
       /courses/test/up: 200
       /profiles/test/up: 200
  - !ruby/object:Jboss 
    deployment_state: old
    name: tabula-secondary
    haproxy_name: secondary
    port: "8180"
    state: running
    mode: smf
    stop_command: "/usr/sbin/svcadm disable -s jboss:"  
    test_path: /home/test/up
    requests: 
       /home/test/up: 200
       /courses/test/up: 200
       /profiles/test/up: 200
lockfile: /tmp/tabula_deploy.running
notification_emails: n.howes@warwick.ac.uk
